"""empty message

迁移 ID: 87c3a8ac9bf5
父迁移:
创建时间: 2024-08-01 09:44:19.285320

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "87c3a8ac9bf5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wakatime", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.String(), nullable=False))
        batch_op.alter_column(
            "access_token",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            nullable=False,
        )
        batch_op.drop_column("user_id")
        batch_op.drop_column("platform")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wakatime", schema=None) as batch_op:
        batch_op.add_column(sa.Column("platform", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=True))
        batch_op.alter_column(
            "access_token", existing_type=sa.String(), type_=sa.INTEGER(), nullable=True
        )
        batch_op.drop_column("id")

    # ### end Alembic commands ###
