"""add subscription table

迁移 ID: e4cefad24e6c
父迁移: 2e39fdc3f6b1
创建时间: 2025-07-29 23:17:36.832208

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e4cefad24e6c"
down_revision: str | Sequence[str] | None = "2e39fdc3f6b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wakatime_subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "target",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wakatime_subscription")),
        info={"bind_key": "nonebot_plugin_wakatime"},
    )
    with op.batch_alter_table("wakatime", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.Integer(), nullable=False))
        batch_op.alter_column(
            "access_token",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=False,
        )
        batch_op.drop_column("user_id")
        batch_op.drop_column("platform")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wakatime", schema=None) as batch_op:
        batch_op.add_column(sa.Column("platform", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("user_id", sa.VARCHAR(), nullable=False))
        batch_op.alter_column(
            "access_token",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )
        batch_op.drop_column("id")

    op.drop_table("wakatime_subscription")
    # ### end Alembic commands ###
